### PR TITLE
open command did not work with pushinsteadof configuration

### PR DESCRIPTION
**Pull request by StephenKing**
If your git/gerrit configuration is based on pushInsteadOf, then the
"open" command did not work.

pusinsteadof can be configured as followed:
git config --global
  url."ssh://username@gerrit.example.org:29418".pushInsteadOf
  git://git.example.org
This way, no different url for "push" has to be configured or manually
entered.

Would be nice, if you could integrate this commit!

Thanks for your work - the script is a great help!
Steffe n

### CODE REVIEW

**Comment by indirect** [comment]
Why vote +1 instead of +2 by default? That's a sort of sneaky change along with the fix for pushinsteadof :)

**Comment by eventualbuddha** [comment]
Agreed, please include only the relevant commits and resubmit the pull request.

**Comment by StephenKing** [comment]
Hi guys,

yes, I somehow mixed it up. I wondered in a later commit, why this one changed the vote line. Copying the file between my /usr/local/bin directory and the git repository was not the smartest idea ;)

I noticed that the approve command uses another approach to retrieve Gerrit's URL (git remote show -n origin | grep "URL:" | head -n1). I'd prefer to use this also for the open command.

However, I have one problem with that, see [1]. I don't know, if it's caused by the pushinsteadof we're using or by sth. else. But by grepping for "URL" you take the Fetch URL, instead of the Push URL (however you always push to Gerrit, but pull from another host, don't you).

So if you give me your OK for this change, I would use this solution also for the open command (in my fork I already did it [2]).

Thanks!
Steffen

[1] https://github.com/StephenKing/gerrit-tools/commit/df29bf64e34d497c5f16fb99e63def302b28193e
[2] https://github.com/StephenKing/gerrit-tools/commit/dbb305204c7239866b3202fd0a2b3c0ddde4625d

**Comment by eventualbuddha** [comment]
I'm not really in a good place to evaluate this at the moment as I no longer have any projects using Gerrit. Andre, perhaps you do?

**Comment by indirect** [comment]
I don't have any Gerrit projects right now, but the change makes sense to me. Stephen, if you submit a new pull request that changes to use the push URL, and doesn't change the vote default, I'll pull it. Thanks!

**Pull request closed without merging**
